const MAP: Record<string, string> = {
  // Рок
  'alisa': 'Алиса',
  'kino': 'Кино',
  'ddt': 'ДДТ',
  'aquarium': 'Аквариум',
  'akvarium': 'Аквариум',
  'nautilus pompilius': 'Наутилус Помпилиус',
  'nautilus': 'Наутилус',
  'aria': 'Ария',
  'agata kristi': 'Агата Кристи',
  'chaif': 'Чайф',
  'piknik': 'Пикник',
  'televizor': 'Телевизор',
  'zoopark': 'Зоопарк',
  'bravo': 'Браво',
  'splean': 'Сплин',
  'splin': 'Сплин',
  'korol i shut': 'Король и Шут',
  "korol' i shut": 'Король и Шут',
  'king and jester': 'Король и Шут',
  'sektor gaza': 'Сектор Газа',
  'sector gaza': 'Сектор Газа',
  'leningrad': 'Ленинград',
  'grazhdanskaya oborona': 'Гражданская Оборона',
  'civil defense': 'Гражданская Оборона',
  'mumiy troll': 'Мумий Тролль',
  'mummy troll': 'Мумий Тролль',
  'bi-2': 'Би-2',
  'bi 2': 'Би-2',
  'zemfira': 'Земфира',
  'chicherina': 'Чичерина',
  'shortparis': 'Shortparis',
  'molchat doma': 'Молчат Дома',
  'car-man': 'Кар-Мэн',
  'kar-men': 'Кар-Мэн',
  'lyube': 'Любэ',
  'lubeh': 'Любэ',
  'mashina vremeni': 'Машина Времени',
  'time machine': 'Машина Времени',
  'crematorium': 'Крематорий',
  'kruiz': 'Круиз',
  'gorky park': 'Горький Парк',
  'master': 'Мастер',
  'черный обелиск': 'Чёрный Обелиск',
  'chyorny obelisk': 'Чёрный Обелиск',
  'black obelisk': 'Чёрный Обелиск',
  'kofe': 'Кофе',
  'televizor': 'Телевизор',

  // Исполнители
  'viktor tsoi': 'Виктор Цой',
  'victor tsoi': 'Виктор Цой',
  'tsoi': 'Цой',
  'vyacheslav butusov': 'Вячеслав Бутусов',
  'viacheslav butusov': 'Вячеслав Бутусов',
  'butusov': 'Бутусов',
  'yuri shevchuk': 'Юрий Шевчук',
  'yury shevchuk': 'Юрий Шевчук',
  'shevchuk': 'Шевчук',
  'boris grebenshchikov': 'Борис Гребенщиков',
  'boris grebenshikov': 'Борис Гребенщиков',
  'garik sukachev': 'Гарик Сукачёв',
  'igor sukachev': 'Игорь Сукачёв',
  'igor talkov': 'Игорь Тальков',
  'talkov': 'Тальков',
  'alla pugacheva': 'Алла Пугачёва',
  'alla pugachyova': 'Алла Пугачёва',
  'pugacheva': 'Пугачёва',
  'pugachyova': 'Пугачёва',
  'filipp kirkorov': 'Филипп Киркоров',
  'philip kirkorov': 'Филипп Киркоров',
  'kirkorov': 'Киркоров',
  'nikolai noskov': 'Николай Носков',
  'noskov': 'Носков',
  'valery meladze': 'Валерий Меладзе',
  'meladze': 'Меладзе',
  'vitas': 'Витас',
  'dima bilan': 'Дима Билан',
  'bilan': 'Билан',
  'alsou': 'Алсу',
  'loboda': 'LOBODA',
  'basta': 'Баста',
  'monetochka': 'Монеточка',
  'pelageya': 'Пелагея',
  'pelageya': 'Пелагея',
  'shaman': 'SHAMAN',
  'polina gagarina': 'Полина Гагарина',
  'gagarina': 'Гагарина',
  'igor krutoy': 'Игорь Крутой',
};

const norm = (s: string) => s.toLowerCase().trim();

export function toCyrillicArtist(name: string): string {
  return MAP[norm(name)] ?? name;
}
